name = "omegle-api-proxy"
main = "worker.js"
compatibility_date = "2026-09-03"
workers_dev = true

routes = [
  { pattern = "api.vitap.in/*", zone_name = "vitap.in" }
]

[vars]
ORIGIN = "http://13.207.9.86.sslip.io"
