apiVersion: v1
kind: Service
metadata:
  name: coturn-lb
  namespace: turn
  labels:
    app: coturn
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: turn-tcp
      port: 3478
      targetPort: 3478
      protocol: TCP
    - name: turn-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
  selector:
    app: coturn
